[package]
name = "cyclic_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
