[package]
name = "cyclic_graph"
version = "0.3.0"
edition = "2024"
authors = ["Sergey Reshetnikov <shaman@simmirra.com>"]
license = "MIT"
repository = "https://github.com/greyshaman/cyclic_graph"
homepage = "https://github.com/greyshaman/cyclic_graph"
keywords = ["graph", "algorithms", "storage"]
readme = "README.md"
description="""
This package provides a way to use a structure that implements
a cyclic directed graph with a single input and single output.
It is designed to be used asynchronously.
"""

[dependencies]
async-recursion = "1.1"
async-trait = "0.1"
futures = { version = "0.3", features = ["futures-executor"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.48", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"]}

[dev-dependencies]

[build-dependencies]
cargo_metadata = "0.23"
